apiVersion: v2
name: namespace-event-exporter
description: A Helm chart for get events and write them to a log service, file, or Stdout
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - https://github.com/resmoio/kubernetes-event-exporter
maintainers:
  - name: eumel8
    email: f.kloeker@telekom.de
    url: https://www.telekom.com
