apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "namespace-event-exporter.labels" . | nindent 4 }}
  name: {{ include "namespace-event-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "namespace-event-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "namespace-event-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
