apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "namespace-event-exporter.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
